stages:
  - test
  - build
  - deploy

#test the frontend application (react)
test:
  stage: test
  image: node:18-alpine
  script: 
    - echo "yarn install"
    - echo "yarn test"

#build docker image for the frontend 
build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script: 
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

#deploy the containers to a remote server 
deploy:
  stage: deploy
  environment:
    name: staging  
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'    
  script:
    - ssh $USER@$HOST "cd sanitrack-backend && docker-compose up -d" 
